export const podcastChannelCollection = [
    {
        id: '97466e0a-3be3-11ed-a261-0242ac12011',
        userId: '00zZuqr5CPUCZJlhnh1zKT2dGVG2',
        creationDate: '2022-09-24T08:34:28Z',
        title: "codewithve's Narrations",
        description: 'A podcast feed for all of codewithve’s narrations. Create once and listen everywhere.',
        email: 'codewithve@gmail.com',
        coverArt: 'https://storage.googleapis.com/ad-auris-mvp-bucket/publication_logo_images/3000x3000%2520logo.png',
        author: 'Ad Auris',
        copyRight: 'Ad Auris 2021',
        language: 'en',
        category1: 'News',
        category2: 'News-Daily News',
        explicit: false,
        site: 'https://play.ad-auris.com',
        date: 'Fri, 09 Sep 2022 03:57:21 GMT'
    },
    {
        id: '97466e0a-3be3-11ed-a261-0242ac12012',
        userId: '094skz1pqbSsHdGHzerFJyGxgzy1',
        creationDate: '2022-09-24T08:34:28Z',
        title: "codewithve's Narrations",
        description: ' A podcast feed for all of codewithve’s narrations. Create once and listen everywhere.',
        email: 'codewithve@gmail.com',
        coverArt: 'https://storage.googleapis.com/ad-auris-mvp-bucket/publication_logo_images/3000x3000%2520logo.png',
        author: 'Ad Auris',
        copyRight: 'Ad Auris 2021',
        language: 'en',
        category1: 'News',
        category2: 'News-Daily News',
        explicit: false,
        site: 'https://play.ad-auris.com',
        date: 'Fri, 09 Sep 2022 03:57:21 GMT'
    },
    {
        id: '97466e0a-3be3-11ed-a261-0242ac12013',
        userId: '0AtiIbMUZDaffHN8aNqlV0CLsep2',
        creationDate: '2022-09-24T08:34:28Z',
        title: "codewithve's Narrations",
        description: ' A podcast feed for all of codewithve’s narrations. Create once and listen everywhere.',
        email: 'codewithve@gmail.com',
        coverArt: 'https://storage.googleapis.com/ad-auris-mvp-bucket/publication_logo_images/3000x3000%2520logo.png',
        author: 'Ad Auris',
        copyRight: 'Ad Auris 2021',
        language: 'en',
        category1: 'News',
        category2: 'News-Daily News',
        explicit: false,
        site: 'https://play.ad-auris.com',
        date: 'Fri, 09 Sep 2022 03:57:21 GMT'
    },
    {
        id: '97466e0a-3be3-11ed-a261-0242ac12014',
        userId: '0C1Qarw88JWOF1Xq1Mo0t2qz7v83',
        creationDate: '2022-09-24T08:34:28Z',
        title: "codewithve's Narrations",
        description: ' A podcast feed for all of codewithve’s narrations. Create once and listen everywhere.',
        email: 'codewithve@gmail.com',
        coverArt: 'https://storage.googleapis.com/ad-auris-mvp-bucket/publication_logo_images/3000x3000%2520logo.png',
        author: 'Ad Auris',
        copyRight: 'Ad Auris 2021',
        language: 'en',
        category1: 'News',
        category2: 'News-Daily News',
        explicit: false,
        site: 'https://play.ad-auris.com',
        date: 'Fri, 09 Sep 2022 03:57:21 GMT'
    },
    {
        id: '97466e0a-3be3-11ed-a261-0242ac12015',
        userId: '0EHW23dMShRozYrvEEOyiF28lYi2',
        creationDate: '2022-09-24T08:34:28Z',
        title: "codewithve's Narrations",
        description: ' A podcast feed for all of codewithve’s narrations. Create once and listen everywhere.',
        email: 'codewithve@gmail.com',
        coverArt: 'https://storage.googleapis.com/ad-auris-mvp-bucket/publication_logo_images/3000x3000%2520logo.png',
        author: 'Ad Auris',
        copyRight: 'Ad Auris 2021',
        language: 'en',
        category1: 'News',
        category2: 'News-Daily News',
        explicit: false,
        site: 'https://play.ad-auris.com',
        date: 'Fri, 09 Sep 2022 03:57:21 GMT'
    }
];
